### ISSUE TITLE
buildx multi-arch runs code under the wrong architecture during build.

### ISSUE THREAD

**Issue by pooley182** [docker/buildx#1046]
I have created a sample docker file below that showcases my issue.
It starts with base Alpine and installs wget, it uses wget to fetch 2 binaries, one for arm64 and one for amd64, it uses the output of `uname -m` to determine system architecture and moves the appropriate binary to the `/usr/local/bin/` folder. Finally it attempts to execute the binary to prove that it has been installed correctly.

```Dockerfile
FROM alpine:latest

RUN apk add --no-cache \
	wget \
  # Install go-replace
    # Fetch AMD64 binary
    && wget -O "/tmp/go-replace-amd" "https://github.com/webdevops/goreplace/releases/download/1.1.2/gr-64-linux" \
    # Fetch ARM64 binary
    && wget -O "/tmp/go-replace-arm" "https://github.com/webdevops/go-replace/releases/download/1.1.2/gr-arm64-linux" \
    # Copy binary into local bin depending on architecture of container
    && if [[ $(uname -m) == *"arm"* || $(uname -m) == *"aarch"* ]]; then cp "/tmp/go-replace-arm" "/usr/local/bin/go-replace"; else cp "/tmp/go-replace-amd" "/usr/local/bin/go-replace"; fi \
    # Make Executable
    && chmod +x "/usr/local/bin/go-replace" \
    # Confirm Installed correctly
    && "/usr/local/bin/go-replace" --version 

```
I am using the docker buildx command `docker buildx build --platform=linux/amd64,linux/arm64 .`

This all works except for the last step when running the binary file. This step always seems to get executed under the host OS's architecture. If I build on an M1 Mac the amd64 build will fail. If I build on an Intel Mac the arm64 build will fail.

Here is the output from my M1 Mac.
```console
> $ docker buildx build --platform=linux/amd64,linux/arm64 .                                                                                           ⬡ 17.8.0
WARNING: No output specified for docker-container driver. Build result will only remain in the build cache. To push result image into registry use --push or to load image into docker use --load
[+] Building 4.5s (9/9) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                        0.0s
 => => transferring dockerfile: 812B                                                                                                                        0.0s
 => [internal] load .dockerignore                                                                                                                           0.0s
 => => transferring context: 2B                                                                                                                             0.0s
 => [linux/arm64 internal] load metadata for docker.io/library/alpine:latest                                                                                1.8s
 => [linux/amd64 internal] load metadata for docker.io/library/alpine:latest                                                                                1.7s
 => [auth] library/alpine:pull token for registry-1.docker.io                                                                                               0.0s
 => CACHED [linux/arm64 1/2] FROM docker.io/library/alpine:latest@sha256:f22945d45ee2eb4dd463ed5a431d9f04fcd80ca768bb1acf898d91ce51f7bf04                   0.0s
 => => resolve docker.io/library/alpine:latest@sha256:f22945d45ee2eb4dd463ed5a431d9f04fcd80ca768bb1acf898d91ce51f7bf04                                      0.0s
 => CACHED [linux/amd64 1/2] FROM docker.io/library/alpine:latest@sha256:f22945d45ee2eb4dd463ed5a431d9f04fcd80ca768bb1acf898d91ce51f7bf04                   0.0s
 => => resolve docker.io/library/alpine:latest@sha256:f22945d45ee2eb4dd463ed5a431d9f04fcd80ca768bb1acf898d91ce51f7bf04                                      0.0s
 => ERROR [linux/amd64 2/2] RUN apk add --no-cache  wget     && wget -O "/tmp/go-replace-amd" "https://github.com/webdevops/goreplace/releases/download/1.  2.4s
 => [linux/arm64 2/2] RUN apk add --no-cache  wget     && wget -O "/tmp/go-replace-amd" "https://github.com/webdevops/goreplace/releases/download/1.1.2/gr  2.2s
------
```
You can see the amd64 build has caused an error. Here is the relevant part of the error log where it attempts to execute the binary with the --version flag
```bash
#0 2.374 runtime: failed to create new OS thread (have 2 already; errno=22)
#0 2.375 fatal error: newosproc
#0 2.378
#0 2.378 runtime stack:
#0 2.379 runtime.throw(0x6430dc, 0x9)
#0 2.380 	/usr/local/Cellar/go/1.8.1/libexec/src/runtime/panic.go:596 +0x95
#0 2.380 runtime.newosproc(0xc420022000, 0xc420032000)
#0 2.380 	/usr/local/Cellar/go/1.8.1/libexec/src/runtime/os_linux.go:163 +0x18c
#0 2.380 runtime.newm(0x650dd0, 0x0)
#0 2.380 	/usr/local/Cellar/go/1.8.1/libexec/src/runtime/proc.go:1628 +0x137
#0 2.380 runtime.main.func1()
#0 2.380 	/usr/local/Cellar/go/1.8.1/libexec/src/runtime/proc.go:126 +0x36
#0 2.380 runtime.systemstack(0x75bb00)
#0 2.380 	/usr/local/Cellar/go/1.8.1/libexec/src/runtime/asm_amd64.s:327 +0x79
#0 2.380 runtime.mstart()
#0 2.380 	/usr/local/Cellar/go/1.8.1/libexec/src/runtime/proc.go:1132
#0 2.380
#0 2.380 goroutine 1 [running]:
#0 2.380 runtime.systemstack_switch()
#0 2.380 	/usr/local/Cellar/go/1.8.1/libexec/src/runtime/asm_amd64.s:281 fp=0xc42001e788 sp=0xc42001e780
#0 2.380 runtime.main()
#0 2.380 	/usr/local/Cellar/go/1.8.1/libexec/src/runtime/proc.go:127 +0x6c fp=0xc42001e7e0 sp=0xc42001e788
#0 2.380 runtime.goexit()
#0 2.380 	/usr/local/Cellar/go/1.8.1/libexec/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc42001e7e8 sp=0xc42001e7e0
```
As you can see from the error it has the src/runtime/asm_amd64.s so the binary is correct, but it fails to execute on the M1 Mac.

I asked my colleague to double check and run the same dockerfile on his Intel Mac and his error was almost identical except referenced the 'src/runtime/asm_arm64.s' file.

---
```console
> $ docker buildx inspect --bootstrap
Name:   interesting_leakey
Driver: docker-container

Nodes:
Name:      interesting_leakey0
Endpoint:  unix:///var/run/docker.sock
Status:    running
Platforms: linux/amd64*, linux/arm64*, linux/amd64/v2, linux/riscv64, linux/ppc64le, linux/s390x, linux/386, linux/mips64le, linux/mips64, linux/arm/v7, linux/arm/v6
```
```console
> $ docker run --privileged --rm tonistiigi/binfmt
{
  "supported": [
    "linux/arm64",
    "linux/amd64",
    "linux/riscv64",
    "linux/ppc64le",
    "linux/s390x",
    "linux/386",
    "linux/mips64le",
    "linux/mips64",
    "linux/arm/v7",
    "linux/arm/v6"
  ],
  "emulators": [
    "qemu-arm",
    "qemu-i386",
    "qemu-mips64",
    "qemu-mips64el",
    "qemu-ppc64le",
    "qemu-riscv64",
    "qemu-s390x",
    "qemu-x86_64"
  ]
}
```

**Comment by tonistiigi** [comment]
This looks like the old https://github.com/linuxkit/linuxkit/issues/1348 issue

I think it appears in here again because the binary is built with very old go1.8 from 2017 that doesn't have the patches.

Also, note that you should not be using `uname -a` for such tasks but define `TARGETARCH` build arg instead. https://docs.docker.com/engine/reference/builder/#automatic-platform-args-in-the-global-scope

**Comment by tonistiigi** [comment]
https://go-review.googlesource.com/c/go/+/48170/ should be related

**Comment by pooley182** [comment]
@tonistiigi Thanks for the info, so is my easiest solution here going to be to grab the source archive from https://github.com/webdevops/goreplace/releases/ and build it myself, using a newer version of go, in the container? Will that successfully create a binary that will run under the correct architecture?

**Comment by pooley182** [comment]
Building the go-replace binary locally with a new version of go resolved my issue.
