### ISSUE TITLE
Bake segfaults on missing function params

### ISSUE THREAD

**Issue by ciaranmcnulty** [docker/buildx#1160]
Reproducer:

```hcl
function "foo" {
  result = "bar"
}
```

Output:
```
[+] Building 0.0s (0/0)                                                                                                                                                     
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x10 pc=0x10454a0a8]

goroutine 1 [running]:
github.com/docker/buildx/bake/hclparser.(*parser).resolveFunction(0x140000aad70, {0x140000553e6, 0x3})
        /src/bake/hclparser/hclparser.go:114 +0x108
github.com/docker/buildx/bake/hclparser.Parse({0x105e89a60, 0x14000113110}, {0x105e36020, 0x140005ef6e0, 0x105e32310}, {0x105cad080, 0x140005ef710})
        /src/bake/hclparser/hclparser.go:360 +0xcb4
```

Docker info:
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.8.2)
  compose: Docker Compose (Docker Inc., v2.5.1)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.17.0)
```

**Comment by ciaranmcnulty** [comment]
I should maybe mention this is using Docker Desktop for Mac on Apple Silicon
