### ISSUE TITLE
Base image not found and other errors

### ISSUE THREAD

**Issue by Andavin** [docker/buildx#1286]
I'm attempting to build an image for my application using a multi-stage Dockerfile with Gradle and OpenJDK as base images.

Here's the Dockerfile:
```dockerfile
ARG JAVA_VERSION
FROM gradle:7.5.1 as build

# Change the work directory to the app root
WORKDIR /app

# Copy all source contents to the build directory
COPY . .

# Execute the build
RUN gradle build

# Create a production stage
FROM openjdk:${JAVA_VERSION}-slim as app

# Change the work directory to the app root
WORKDIR /app
# Declare the version for use in the next step
ARG APP_VERSION
# Copy the JAR from the build directory in the previous stage
COPY --from=build /app/build/libs/app-jvm-$APP_VERSION.jar app-$APP_VERSION.jar

# Execute the startup command
CMD [ "java", "-jar", "app-$APP_VERSION.jar" ]
```

The script I'm using to export environment variables and subsequently run the buildx bake command is:
```shell
#!/bin/bash
# shellcheck disable=SC2046
#
# This script is intended to deploy all Docker images to the registry
# 1. Read all build environment variables from .env
# 2. Login to the Docker registry
# 3. Build and push all images with Docker buildx
#
# Export all the environment variables that are present in .env
echo "Exporting all variables from .env"
export $(grep -v '^#' .env | xargs -d '\n')

# Login to the registry if it ends in .com
if [[ $REGISTRY == *.com ]]; then
  echo "Logging in to https://$REGISTRY Docker registry"
  docker login https://"$REGISTRY"
fi

# Build and push with buildx bake using the docker compose file
echo "Building and pushing images"
docker buildx bake -f docker-compose.yml --push
```

When building the image with `docker compose build`, everything works.
The issue is that when running the script (or even the command directly after exporting the variables), errors are produced at unusual places.

With the Dockerfile above, running the command produces the following error (FYI making the variable explicit changes nothing either):
```
--------------------
  14 |
  15 |     # Create a production stage
  16 | >>> FROM openjdk:${JAVA_VERSION}-slim as app
  17 |
  18 |     # Change the work directory to the app root
--------------------
error: failed to solve: openjdk:17.0.2-slim: no match for platform in manifest sha256:aaa3b3cb27e3e520b8f116863d0580c438ed55ecfa0bc126b41f68c3f62f9774: not found
```

If I change the base image to some other Java based image such as `gradle:7.5.1`, then I get another error:
```
------
 > [app linux/arm/v7 build 4/4] RUN gradle build:
#0 1.199 org.gradle.api.internal.classpath.UnknownModuleException: Cannot locate JAR for module 'ant' in distribution directory '/opt/gradle'.
#0 1.202        at org.gradle.api.internal.classpath.DefaultModuleRegistry.loadExternalModule(DefaultModuleRegistry.java:109)
#0 1.202        at org.gradle.api.internal.classpath.DefaultModuleRegistry.getExternalModule(DefaultModuleRegistry.java:97)
#0 1.202        at org.gradle.api.internal.DefaultClassPathProvider.findClassPath(DefaultClassPathProvider.java:70)
#0 1.202        at org.gradle.api.internal.DefaultClassPathRegistry.getClassPath(DefaultClassPathRegistry.java:35)
#0 1.202        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:48)
#0 1.203        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
#0 1.203        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
#0 1.203        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
#0 1.203        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
#0 1.203        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
#0 1.204        at org.gradle.launcher.GradleMain.main(GradleMain.java:34)
------

--------------------
   9 |
  10 |     # Execute the build
  11 | >>> RUN gradle build
  12 |
  13 |     # Create a production stage
--------------------
error: failed to solve: process "/bin/sh -c gradle build" did not complete successfully: exit code: 1
```
Further examination of the `gradle:7.5.1` image reveals that /opt/gradle DOES indeed have ant modules available.

Since the build is successful and none of these issues show themselves when running `docker compose build`, it seems that this has to do with buildx.

I'm running Windows 10 with WSL Debian. Note that I've also tried restarting docker, clearing caches, enabling experimental mode, changing out all variables for explicit versions and even running it on a different machine (an Ubuntu server).

Buildx Version:
`github.com/docker/buildx v0.8.2 6224def4dd2c3d347eee19db595348c50d7cb491`

Docker Version: 
```shell
Client:
 Cloud integration: v1.0.28
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:09:02 2022
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.11.1 (84025)
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:23 2022
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.6.6
  GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc:
  Version:          1.1.2
  GitCommit:        v1.1.2-0-ga916309
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by Andavin** [comment]
It looks like I've completely missed the error about the platform and I'm guessing there is no OpenJDK image for arm/v7. The Gradle issue still has me confused
