### ISSUE TITLE
buildx cannot handle contexts whose name starts with a number

### ISSUE THREAD

**Issue by IJMacD** [docker/buildx#1956]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/buildx/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

`docker context` allows creation of contexts with names that start with a number e.g.

    docker context create first-demo --docker "host=ssh://user@host"
    docker context create 2nd-demo --docker "host=ssh://user@host"

Buildx can't handle contexts which start with a number

### Expected behaviour

```
$ docker context use first-demo
first-demo
Current context is now "first-demo"
$ docker buildx inspect
Name:   first-demo
Driver: docker

Nodes:
Name:      first-demo
Endpoint:  first-demo
Status:    running
Buildkit:  v0.11.7-0.20230525183624-798ad6b0ce9f
Platforms: linux/amd64, linux/amd64/v2, linux/386
```

### Actual behaviour

```
$ docker context use 2nd-demo
2nd-demo
Current context is now "2nd-demo"
$ docker buildx inspect
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x10e1437]

goroutine 1 [running]:
github.com/docker/buildx/builder.(*Builder).LoadNodes(0xc0001bec60, {0x23dd0c0, 0xc0002b9e30}, 0x1)
        github.com/docker/buildx/builder/node.go:41 +0xd7
github.com/docker/buildx/commands.runInspect({0x23eebc0, 0xc0000b6500}, {0x0?, {0x0?, 0x0?}})
        github.com/docker/buildx/commands/inspect.go:38 +0x17a
github.com/docker/buildx/commands.inspectCmd.func1(0xc0002a4c00?, {0x33c98a8?, 0x0?, 0x0?})
        github.com/docker/buildx/commands/inspect.go:113 +0x9f
github.com/spf13/cobra.(*Command).execute(0xc0002a4c00, {0xc0001d8e70, 0x0, 0x0})
        github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002b4c00)
        github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.6.1/command.go:968
github.com/docker/cli/cli-plugins/plugin.RunPlugin(0x1d941a0?, 0xc00034b500, {{0x209a919, 0x5}, {0x20a4b3b, 0xb}, {0x23b95f0, 0x7}, {0x0, 0x0}, ...})
        github.com/docker/cli@v23.0.0-rc.1+incompatible/cli-plugins/plugin/plugin.go:51 +0x130
main.runPlugin(0x20dee13?)
        github.com/docker/buildx/cmd/buildx/main.go:45 +0x105
main.main()
        github.com/docker/buildx/cmd/buildx/main.go:62 +0xf9
```

### Buildx version

github.com/docker/buildx v0.10.5 86bdced

### Docker info

```text
Client: Docker Engine - Community
 Version:    24.0.2
 Context:    2nd-demo
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.5
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.18.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 24.0.4
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.10.0-23-amd64
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: x86_64
 CPUs: 32
 Total Memory: 31.34GiB
 Name: DCP-DED542
 ID: eebe7550-62f3-4737-8544-8519a980dab2
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Builders list

```text
$ docker buildx ls
ERROR: invalid name 2nd-demo, name needs to start with a letter and may not contain symbols, except ._-
$ docker context remove 2nd-demo
2nd-demo
$ docker buildx ls
NAME/NODE           DRIVER/ENDPOINT   STATUS  BUILDKIT                              PLATFORMS
default                               error
first-demo *        docker
  first-demo        first-demo        running v0.11.7-0.20230525183624-798ad6b0ce9f linux/amd64, linux/amd64/v2, linux/386
```

### Configuration

Dockerfile:
```dockerfile
FROM alpine
CMD echo hello
```

docker-compose.yml:
```yml
services:
  hello:
    build: .
```

```console
$ docker context create 2nd-demo --docker "host=ssh://user@host"
$ docker context use 2nd-demo
$ docker compose -f docker-compose.yml up --build -d
```

**Comment by jedevc** [comment]
This should be fixed by https://github.com/docker/buildx/pull/1879 🎉

This fix is in the latest buildx release, so just upgrading should resolve the issue.

@IJMacD I'll close this issue, but if you can reproduce this on the latest buildx release, let me know!
