### ISSUE TITLE
Building Go app on multi-arch (amd64/arm64/ppc64le) fails on ppc64le

### ISSUE THREAD

**Issue by carlosedp** [docker/buildx#242]
While trying to build a multi-arch application using buildx on Docker for Mac, I got the error below on the ppc64 build:

```
❯ DOCKER_BUILDKIT=1 docker buildx build --platform linux/arm64,linux/amd64,linux/ppc64le -t carlosedp/keycloak-gatekeeper:v9.0.0 .
WARN[0000] No output specified for docker-container driver. Build result will only remain in the build cache. To push result image into registry use --push or to load image into docker use --load
[+] Building 78.2s (37/41)
 => [internal] load build definition from Dockerfile                                                                                                                                    0.0s
 => => transferring dockerfile: 32B                                                                                                                                                     0.0s
 => [internal] load .dockerignore                                                                                                                                                       0.0s
 => => transferring context: 2B                                                                                                                                                         0.0s
 => [linux/ppc64le internal] load metadata for registry.access.redhat.com/ubi8-minimal:latest                                                                                           1.7s
 => [linux/ppc64le internal] load metadata for docker.io/library/golang:1.14                                                                                                            2.1s
 => [linux/arm64 internal] load metadata for registry.access.redhat.com/ubi8-minimal:latest                                                                                             1.5s
 => [linux/arm64 internal] load metadata for docker.io/library/golang:1.14                                                                                                              1.9s
 => [linux/amd64 internal] load metadata for docker.io/library/golang:1.14                                                                                                              1.9s
 => [linux/amd64 internal] load metadata for registry.access.redhat.com/ubi8-minimal:latest                                                                                             1.5s
 => [linux/arm64 stage-1 1/8] FROM registry.access.redhat.com/ubi8-minimal@sha256:01b8fb7b3ad16a575651a4e007e8f4d95b68f727b3a41fc57996be9a790dc4fa                                      0.0s
 => => resolve registry.access.redhat.com/ubi8-minimal@sha256:01b8fb7b3ad16a575651a4e007e8f4d95b68f727b3a41fc57996be9a790dc4fa                                                          0.0s
 => [linux/arm64 builder 1/3] FROM docker.io/library/golang:1.14@sha256:d27017d27f9c9a58b361aa36126a29587ffd3b1b274af0d583fe4954365a4a59                                                0.0s
 => => resolve docker.io/library/golang:1.14@sha256:d27017d27f9c9a58b361aa36126a29587ffd3b1b274af0d583fe4954365a4a59                                                                    0.0s
 => CACHED [linux/arm64 builder 2/3] WORKDIR /go/src/app                                                                                                                                0.0s
 => CACHED [linux/arm64 stage-1 2/8] WORKDIR /opt/gatekeeper                                                                                                                            0.0s
 => CACHED [linux/arm64 stage-1 3/8] RUN echo "gatekeeper:x:1000:gatekeeper" >> /etc/group                                                                                              0.0s
 => CACHED [linux/arm64 stage-1 4/8] RUN echo "gatekeeper:x:1000:1000:gatekeeper user:/opt/gatekeeper:/sbin/nologin" >> /etc/passwd                                                     0.0s
 => CACHED [linux/arm64 stage-1 5/8] RUN chown -R gatekeeper:gatekeeper /opt/gatekeeper && chmod -R g+rw /opt/gatekeeper                                                                0.0s
 => CACHED [linux/arm64 stage-1 6/8] RUN microdnf update -y && microdnf install -y ca-certificates                                                                                      0.0s
 => CANCELED [linux/arm64 builder 3/3] RUN git clone https://github.com/keycloak/keycloak-gatekeeper.git -b 9.0.0 --depth=1 &&     cd keycloak-gatekeeper &&     GOOS=linux GOARCH=am  76.2s
 => [linux/amd64 stage-1 1/8] FROM registry.access.redhat.com/ubi8-minimal@sha256:01b8fb7b3ad16a575651a4e007e8f4d95b68f727b3a41fc57996be9a790dc4fa                                      0.0s
 => => resolve registry.access.redhat.com/ubi8-minimal@sha256:01b8fb7b3ad16a575651a4e007e8f4d95b68f727b3a41fc57996be9a790dc4fa                                                          0.0s
 => [linux/amd64 builder 1/3] FROM docker.io/library/golang:1.14@sha256:d27017d27f9c9a58b361aa36126a29587ffd3b1b274af0d583fe4954365a4a59                                                0.0s
 => => resolve docker.io/library/golang:1.14@sha256:d27017d27f9c9a58b361aa36126a29587ffd3b1b274af0d583fe4954365a4a59                                                                    0.0s
 => CACHED [linux/amd64 stage-1 2/8] WORKDIR /opt/gatekeeper                                                                                                                            0.0s
 => CACHED [linux/amd64 stage-1 3/8] RUN echo "gatekeeper:x:1000:gatekeeper" >> /etc/group                                                                                              0.0s
 => CACHED [linux/amd64 stage-1 4/8] RUN echo "gatekeeper:x:1000:1000:gatekeeper user:/opt/gatekeeper:/sbin/nologin" >> /etc/passwd                                                     0.0s
 => CACHED [linux/amd64 stage-1 5/8] RUN chown -R gatekeeper:gatekeeper /opt/gatekeeper && chmod -R g+rw /opt/gatekeeper                                                                0.0s
 => CACHED [linux/amd64 stage-1 6/8] RUN microdnf update -y && microdnf install -y ca-certificates                                                                                      0.0s
 => CACHED [linux/amd64 builder 2/3] WORKDIR /go/src/app                                                                                                                                0.0s
 => CACHED [linux/amd64 builder 3/3] RUN git clone https://github.com/keycloak/keycloak-gatekeeper.git -b 9.0.0 --depth=1 &&     cd keycloak-gatekeeper &&     GOOS=linux GOARCH=amd64  0.0s
 => CACHED [linux/amd64 stage-1 7/8] COPY --from=builder /keycloak-gatekeeper /opt/gatekeeper/keycloak-gatekeeper                                                                       0.0s
 => [linux/amd64 stage-1 8/8] RUN microdnf clean all                                                                                                                                    0.2s
 => [linux/ppc64le stage-1 1/8] FROM registry.access.redhat.com/ubi8-minimal@sha256:01b8fb7b3ad16a575651a4e007e8f4d95b68f727b3a41fc57996be9a790dc4fa                                    0.0s
 => => resolve registry.access.redhat.com/ubi8-minimal@sha256:01b8fb7b3ad16a575651a4e007e8f4d95b68f727b3a41fc57996be9a790dc4fa                                                          0.0s
 => [linux/ppc64le builder 1/3] FROM docker.io/library/golang:1.14@sha256:d27017d27f9c9a58b361aa36126a29587ffd3b1b274af0d583fe4954365a4a59                                              0.0s
 => => resolve docker.io/library/golang:1.14@sha256:d27017d27f9c9a58b361aa36126a29587ffd3b1b274af0d583fe4954365a4a59                                                                    0.0s
 => CACHED [linux/ppc64le stage-1 2/8] WORKDIR /opt/gatekeeper                                                                                                                          0.0s
 => CACHED [linux/ppc64le stage-1 3/8] RUN echo "gatekeeper:x:1000:gatekeeper" >> /etc/group                                                                                            0.0s
 => [linux/ppc64le stage-1 4/8] RUN echo "gatekeeper:x:1000:1000:gatekeeper user:/opt/gatekeeper:/sbin/nologin" >> /etc/passwd                                                          0.3s
 => CACHED [linux/ppc64le builder 2/3] WORKDIR /go/src/app                                                                                                                              0.0s
 => ERROR [linux/ppc64le builder 3/3] RUN git clone https://github.com/keycloak/keycloak-gatekeeper.git -b 9.0.0 --depth=1 &&     cd keycloak-gatekeeper &&     GOOS=linux GOARCH=amd  75.7s
 => [linux/ppc64le stage-1 5/8] RUN chown -R gatekeeper:gatekeeper /opt/gatekeeper && chmod -R g+rw /opt/gatekeeper                                                                     0.3s
 => [linux/ppc64le stage-1 6/8] RUN microdnf update -y && microdnf install -y ca-certificates                                                                                          38.1s
------
 > [linux/ppc64le builder 3/3] RUN git clone https://github.com/keycloak/keycloak-gatekeeper.git -b 9.0.0 --depth=1 &&     cd keycloak-gatekeeper &&     GOOS=linux GOARCH=amd64 make &&     mv bin/keycloak-gatekeeper /keycloak-gatekeeper:
#39 0.218 Cloning into 'keycloak-gatekeeper'...
#39 2.722 Note: checking out '4293a9b83d661dec8930b1284ce2f44ffd89aa18'.
#39 2.722
#39 2.722 You are in 'detached HEAD' state. You can look around, make experimental
#39 2.722 changes and commit them, and you can discard any commits you make in this
#39 2.722 state without impacting any branches by performing another checkout.
#39 2.722
#39 2.722 If you want to create a new branch to retain commits you create, you may
#39 2.722 do so (now or later) by using -b with the checkout command again. Example:
#39 2.722
#39 2.722   git checkout -b <new-branch-name>
#39 2.722
#39 2.844 --> Go Version
#39 2.976 go version go1.14 linux/ppc64le
#39 3.157 --> Compiling the project
#39 3.201 go build -ldflags "-X main.gitsha=4293a9b -X main.compiled=1584467905" -o bin/keycloak-gatekeeper
#39 6.753 go: downloading github.com/armon/go-proxyproto v0.0.0-20180202201750-5b7edb60ff5f
#39 6.757 go: downloading github.com/go-chi/chi v3.3.3+incompatible
#39 6.759 go: downloading github.com/urfave/cli v0.0.0-20181029213200-b67dcf995b6a
#39 6.775 go: downloading golang.org/x/crypto v0.0.0-20181203042331-505ab145d0a9
#39 6.778 go: downloading github.com/satori/go.uuid v1.2.0
#39 6.781 go: downloading github.com/coreos/go-oidc v0.0.0-20171020180921-e860bd55bfa7
#39 6.793 go: downloading gopkg.in/redis.v4 v4.2.4
#39 6.823 go: downloading github.com/PuerkitoBio/purell v1.1.0
#39 6.958 go: downloading go.uber.org/zap v1.9.1
#39 7.025 go: downloading github.com/fsnotify/fsnotify v1.4.7
#39 7.408 go: downloading github.com/unrolled/secure v0.0.0-20181221173256-0d6b5bb13069
#39 7.589 go: downloading golang.org/x/net v0.0.0-20181201002055-351d144fa1fc
#39 7.624 go: downloading github.com/rs/cors v1.6.0
#39 7.813 go: downloading github.com/prometheus/client_golang v0.9.2
#39 7.848 go: downloading golang.org/x/sys v0.0.0-20190329044733-9eb1bfa1ce65
#39 8.012 go: downloading github.com/boltdb/bolt v1.3.1
#39 8.018 go: downloading gopkg.in/yaml.v2 v2.2.2
#39 8.114 go: downloading golang.org/x/text v0.3.0
#39 8.607 go: downloading go.uber.org/atomic v1.3.2
#39 8.688 go: downloading github.com/PuerkitoBio/urlesc v0.0.0-20170810143723-de5bf2ad4578
#39 8.730 go: downloading github.com/coreos/pkg v0.0.0-20180928190104-399ea9e2e55f
#39 8.879 go: downloading go.uber.org/multierr v1.1.0
#39 9.072 go: downloading github.com/jonboulle/clockwork v0.1.0
#39 9.225 go: downloading github.com/prometheus/client_model v0.0.0-20180712105110-5c3871d89910
#39 9.267 go: downloading github.com/golang/protobuf v1.2.0
#39 9.387 go: downloading github.com/elazarl/goproxy v0.0.0-20181111060418-2ce16c963a8a
#39 9.422 go: downloading github.com/prometheus/procfs v0.0.0-20181204211112-1dc9a6cbc91a
#39 9.734 go: downloading gopkg.in/bsm/ratelimit.v1 v1.0.0-20160220154919-db14e161995a
#39 9.930 go: downloading github.com/prometheus/common v0.0.0-20181126121408-4724e9255275
#39 10.09 go: downloading github.com/beorn7/perks v0.0.0-20180321164747-3a771d992973
#39 10.70 go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.1
#39 75.17 # runtime
#39 75.17 /usr/local/go/src/runtime/runtime1.go:162:22: internal compiler error: 'check': panic during opt while compiling check:
#39 75.17
#39 75.17 truncate64Fto32F: truncation is not exact
#39 75.17
#39 75.17 goroutine 163 [running]:
#39 75.17 cmd/compile/internal/ssa.Compile.func1(0xc0039ccf00, 0xc0041a1080)
#39 75.17 	/usr/local/go/src/cmd/compile/internal/ssa/compile.go:47 +0x9c
#39 75.17 panic(0x8feba0, 0xb54130)
#39 75.17 	/usr/local/go/src/runtime/panic.go:967 +0x14c
#39 75.17 cmd/compile/internal/ssa.truncate64Fto32F(0xc7ffffffe0000000, 0xc0000008d5)
#39 75.17 	/usr/local/go/src/cmd/compile/internal/ssa/rewrite.go:455 +0xd4
#39 75.17 cmd/compile/internal/ssa.auxTo32F(...)
#39 75.17 	/usr/local/go/src/cmd/compile/internal/ssa/rewrite.go:500
#39 75.17 cmd/compile/internal/ssa.rewriteValuegeneric_OpEq32F_0(0xc0029f0ae8, 0xffffffffffffff01)
#39 75.17 	/usr/local/go/src/cmd/compile/internal/ssa/rewritegeneric.go:18633 +0x128
#39 75.17 cmd/compile/internal/ssa.rewriteValuegeneric(0xc0029f0ae8, 0x0)
#39 75.17 	/usr/local/go/src/cmd/compile/internal/ssa/rewritegeneric.go:96 +0x191c
#39 75.17 cmd/compile/internal/ssa.applyRewrite(0xc0041a1080, 0x9a5e88, 0x9a5f08)
#39 75.17 	/usr/local/go/src/cmd/compile/internal/ssa/rewrite.go:81 +0x574
#39 75.17 cmd/compile/internal/ssa.opt(0xc0041a1080)
#39 75.17 	/usr/local/go/src/cmd/compile/internal/ssa/opt.go:9 +0x44
#39 75.17 cmd/compile/internal/ssa.Compile(0xc0041a1080)
#39 75.17 	/usr/local/go/src/cmd/compile/internal/ssa/compile.go:92 +0x878
#39 75.17 cmd/compile/internal/gc.buildssa(0xc00197bb80, 0x3, 0x0)
#39 75.17 	/usr/local/go/src/cmd/compile/internal/gc/ssa.go:445 +0x860
#39 75.17 cmd/compile/internal/gc.compileSSA(0xc00197bb80, 0x3)
#39 75.17 	/usr/local/go/src/cmd/compile/internal/gc/pgen.go:298 +0x44
#39 75.17 cmd/compile/internal/gc.compileFunctions.func2(0xc0039b2540, 0xc00093b460, 0x3)
#39 75.17 	/usr/local/go/src/cmd/compile/internal/gc/pgen.go:363 +0x40
#39 75.17 created by cmd/compile/internal/gc.compileFunctions
#39 75.17 	/usr/local/go/src/cmd/compile/internal/gc/pgen.go:361 +0x12c
#39 75.17
#39 75.17
#39 75.17
#39 75.17 Please file a bug report including a short program that triggers the error.
#39 75.17 https://golang.org/issue/new
#39 75.53 make: *** [Makefile:28: build] Error 2
------
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to build LLB: executor failed running [/bin/sh -c git clone https://github.com/keycloak/keycloak-gatekeeper.git -b $VERSION --depth=1 &&     cd keycloak-gatekeeper &&     GOOS=$TARGETOS GOARCH=$TARGETARCH make &&     mv bin/keycloak-gatekeeper /keycloak-gatekeeper]: buildkit-runc did not terminate sucessfully
```
The Dockerfile I'm building is:

```
# Building on Docker buildx
# docker buildx build --platform linux/arm64,linux/amd64,linux/ppc64le -t repo/keycloak-gatekeeper:v9.0.0 . --push
# docker buildx build --platform linux/arm64,linux/amd64,linux/ppc64le --build-arg VERSION=8.0.0 -t repo/keycloak-gatekeeper:v8.0.0 . --push
# docker buildx build --platform linux/arm64,linux/amd64,linux/ppc64le --build-arg VERSION=master -t repo/keycloak-gatekeeper:latest . --push

# Build on Docker
# For the default os/arch (linux/amd64) and version (9.0.0)
# docker build -t repo/keycloak-gatekeeper:v9.0.0 .

# Builder container
FROM golang:1.14 as builder

ARG TARGETOS=linux
ARG TARGETARCH=amd64
ARG VERSION=9.0.0

WORKDIR $GOPATH/src/app

RUN git clone https://github.com/keycloak/keycloak-gatekeeper.git -b $VERSION --depth=1 && \
    cd keycloak-gatekeeper && \
    GOOS=$TARGETOS GOARCH=$TARGETARCH make && \
    mv bin/keycloak-gatekeeper /keycloak-gatekeeper

# Application Container
FROM registry.access.redhat.com/ubi8-minimal

ARG TARGETOS=linux
ARG TARGETARCH=amd64
ARG VERSION=9.0.0
ENV NAME keycloak-gatekeeper
ENV KEYCLOAK_VERSION $VERSION
ENV GOOS $TARGETOS
ENV GOARCH $TARGETARCH

LABEL Name=keycloak-gatekeeper \
    Release=https://github.com/keycloak/keycloak-gatekeeper \
    Url=https://github.com/keycloak/keycloak-gatekeeper \
    Help=https://issues.jboss.org/projects/KEYCLOAK

USER root

WORKDIR "/opt/gatekeeper"

RUN echo "gatekeeper:x:1000:gatekeeper" >> /etc/group
RUN echo "gatekeeper:x:1000:1000:gatekeeper user:/opt/gatekeeper:/sbin/nologin" >> /etc/passwd
RUN chown -R gatekeeper:gatekeeper /opt/gatekeeper && chmod -R g+rw /opt/gatekeeper

RUN microdnf update -y && microdnf install -y ca-certificates

COPY --from=builder /keycloak-gatekeeper /opt/gatekeeper/keycloak-gatekeeper

RUN microdnf clean all

USER 1000

ENTRYPOINT [ "/opt/gatekeeper/keycloak-gatekeeper" ]
```

My Docker info is:

```
❯ docker run ppc64le/alpine sh -c "/proc/1/exe --version"
qemu-ppc64le version 4.1.0 (v4.1.0)
Copyright (c) 2003-2019 Fabrice Bellard and the QEMU Project developers

❯ docker version
Client:
 Version:           unknown-version
 API version:       1.40 (downgraded from 1.41)
 Go version:        devel +c20db960e2 3 weeks ago
 Git commit:        ba63a926
 Built:             Fri Dec 27 17:31:05 2019
 OS/Arch:           darwin/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

<img width="757" alt="image" src="https://user-images.githubusercontent.com/20382/76889644-b9b6ba80-6864-11ea-80d6-af9b03e63247.png">

I have a local PPC64le Qemu VM with Debian 10 and have been able to build the project successfully (with go build .). I tested on Qemu 4.1.50 and 4.2.50.

```
❯ qemu-system-ppc64 --version
QEMU emulator version 4.1.50 (v4.1.0-405-g586f3dced9-dirty)
Copyright (c) 2003-2019 Fabrice Bellard and the QEMU Project developers

❯ uname -a
Linux debian-ppc64 5.5.0-rc5-powerpc64le #1 SMP Debian 5.5~rc5-1~exp1 (2020-01-06) ppc64le GNU/Linux
❯ lscpu
Architecture:        ppc64le
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per socket:  4
Socket(s):           1
NUMA node(s):        1
Model:               2.0 (pvr 004e 1200)
Model name:          POWER9 (architected), altivec supported
Hypervisor vendor:   KVM
Virtualization type: para
L1d cache:           32K
L1i cache:           32K
NUMA node0 CPU(s):   0-3


❯ make
--> Go Version
go version go1.14 linux/ppc64le
--> Compiling the project
go build -ldflags "-X main.gitsha=b04d526-dirty -X main.compiled=1584469899" -o bin/keycloak-gatekeeper
❯ file bin/keycloak-gatekeeper
bin/keycloak-gatekeeper: ELF 64-bit LSB executable, 64-bit PowerPC or cisco 7500, version 1 (SYSV), dynamically linked, interpreter /lib64/ld64.so.2, for GNU/Linux 3.10.0, Go BuildID=klUAbk_ak1-Mxj8zJJBp/T3epReHn3ztGjHY3HjDV/_uwB9mC4X9Y-HrosDZyw/YKhb2Qa1xGJuKrLpOnw7, BuildID[sha1]=ed12c55f1a8a6fb6beca8e35a9ea90334b30f4a9, not stripped
```

**Comment by carlosedp** [comment]
Weirdly, if I build manually inside the a ppc64le container (in the same Macbook laptop), it works:

```bash
❯ docker run -it --rm --platform=ppc64le golang:1.14
root@50ca58cbeacc:/go/keycloak-gatekeeper# uname -a
Linux 50ca58cbeacc 4.19.76-linuxkit #1 SMP Thu Oct 17 19:31:58 UTC 2019 ppc64le GNU/Linux
root@50ca58cbeacc:/go# /proc/1/exe --version
qemu-ppc64le version 4.1.0 (v4.1.0)
Copyright (c) 2003-2019 Fabrice Bellard and the QEMU Project developers
root@50ca58cbeacc:/go#
root@50ca58cbeacc:/go# ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.7  0.3 126656 14684 pts/0    Ssl  18:36   0:00 /usr/bin/qemu-ppc64le /bin/bash
root        17  0.0  0.2 128276 11464 ?        Rl+  Mar14   0:00 /bin/ps aux
root@50ca58cbeacc:/go# pwd
/go
root@50ca58cbeacc:/go# git clone https://github.com/keycloak/keycloak-gatekeeper --depth=1
Cloning into 'keycloak-gatekeeper'...
remote: Enumerating objects: 68, done.
remote: Counting objects: 100% (68/68), done.
remote: Compressing objects: 100% (68/68), done.
remote: Total 68 (delta 3), reused 24 (delta 0), pack-reused 0
Unpacking objects: 100% (68/68), done.
root@50ca58cbeacc:/go#
root@50ca58cbeacc:/go# cd keycloak-gatekeeper/
root@50ca58cbeacc:/go/keycloak-gatekeeper# make
--> Go Version
go version go1.14 linux/ppc64le
--> Compiling the project
go build -ldflags "-X main.gitsha=b04d526 -X main.compiled=1584470290" -o bin/keycloak-gatekeeper
go: downloading github.com/PuerkitoBio/purell v1.1.0
go: downloading github.com/prometheus/client_golang v0.9.2
go: downloading github.com/unrolled/secure v0.0.0-20181221173256-0d6b5bb13069
go: downloading go.uber.org/zap v1.9.1
go: downloading github.com/urfave/cli v0.0.0-20181029213200-b67dcf995b6a
go: downloading github.com/fsnotify/fsnotify v1.4.7
go: downloading github.com/elazarl/goproxy v0.0.0-20181111060418-2ce16c963a8a
go: downloading gopkg.in/redis.v4 v4.2.4
go: downloading github.com/coreos/go-oidc v0.0.0-20171020180921-e860bd55bfa7
go: downloading golang.org/x/net v0.0.0-20181201002055-351d144fa1fc
go: downloading github.com/go-chi/chi v3.3.3+incompatible
go: downloading github.com/PuerkitoBio/urlesc v0.0.0-20170810143723-de5bf2ad4578
go: downloading golang.org/x/sys v0.0.0-20200302083256-062a44052db1
go: downloading github.com/jonboulle/clockwork v0.1.0
go: downloading golang.org/x/text v0.3.0
go: downloading github.com/prometheus/common v0.0.0-20181126121408-4724e9255275
go: downloading go.uber.org/atomic v1.3.2
go: downloading github.com/coreos/pkg v0.0.0-20180928190104-399ea9e2e55f
go: downloading github.com/beorn7/perks v0.0.0-20180321164747-3a771d992973
go: downloading github.com/rs/cors v1.6.0
go: downloading github.com/prometheus/procfs v0.0.0-20181204211112-1dc9a6cbc91a
go: downloading github.com/golang/protobuf v1.2.0
go: downloading gopkg.in/yaml.v2 v2.2.2
go: downloading github.com/prometheus/client_model v0.0.0-20180712105110-5c3871d89910
go: downloading github.com/satori/go.uuid v1.2.0
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.1
go: downloading go.uber.org/multierr v1.1.0
go: downloading github.com/armon/go-proxyproto v0.0.0-20180202201750-5b7edb60ff5f
go: downloading golang.org/x/crypto v0.0.0-20181203042331-505ab145d0a9
go: downloading github.com/etcd-io/bbolt v1.3.3
go: downloading gopkg.in/bsm/ratelimit.v1 v1.0.0-20160220154919-db14e161995a
root@50ca58cbeacc:/go/keycloak-gatekeeper#
root@50ca58cbeacc:/go/keycloak-gatekeeper# file bin/keycloak-gatekeeper
root@50ca58cbeacc:/go/keycloak-gatekeeper# file bin/keycloak-gatekeeper
bin/keycloak-gatekeeper: ELF 64-bit LSB executable, 64-bit PowerPC or cisco 7500, version 1 (SYSV), dynamically linked, interpreter /lib64/ld64.so.2, for GNU/Linux 3.10.0, Go BuildID=qHm4lyKRIAO3x-OZyTRC/3mDY7Js8jMgQBK0YSeWb/mYcbQst4sQL2qKvU_08x/kTwfeD9djfimi7qFBXtx, BuildID[sha1]=66ea98cd054aa192dbcd9f65e8e1e30e4fe2e1df, not stripped
```

**Comment by tonistiigi** [comment]
The issue (or at least difference between build and run) is

```
ARG TARGETOS=linux
ARG TARGETARCH=amd64
```

This means that unless you set `--build-arg TARGETARCH=ppc64le` manually `GOARCH` will always be `amd64`, even if you set another value with `--platform`. The order of precedence for the arg values is 1) user-defined value 2) default in ARG definition 3) default in global scope `ARG` definition 4) implicit value (eg. from `--platform`).

So you just need to set these lines to:

```
ARG TARGETOS
ARG TARGETARCH
```

if you want the value from `--platform`.

If you do `docker run --platform=ppc64le` and call `GOARCH=amd64 make` from there you will get the same error. That is a `qemu` (or `go`) error and should be tracked in their repos and possibly backported to https://github.com/moby/moby is upstream doesn't take the patch for some reason.

**Comment by carlosedp** [comment]
Wow, thanks a lot Tonis, I thought the arguments from --platform had precedence over the default args inside the Dockerfile.

I just tested without the defaults in the Dockerfile and it worked fine. I think this is something related to Qemu/PPC64le since it doesn't happen on other archs.
