### ISSUE TITLE
`panic: runtime error: integer divide by zero` when attempting to use an existing k8s buildkit deployment

### ISSUE THREAD

**Issue by metasim** [docker/buildx#961]
I'm attempting to connect to an existing buildkit deployment in our Kubernetes cluster. I'd like to be able to reuse an existing deployment for multiple clients rather than having to have separate ones running. The documentation isn't clear on whether this is possible or not, but when I try the command below, the CLI panics.

### Command

```
docker -D buildx create \
	--name k8s-build --node buildkit \
	--driver=kubernetes \
	--platform linux/amd64 \
	--driver-opt=namespace=buildkit
```

### Output 

```
DEBU[0000] using default config store "/Users/xxx/.docker/buildx"
DEBU[0000] pod runnning: "buildkit-7cd447d558-rq4fw"
ERRO[0001] no pod found for key ""
panic: runtime error: integer divide by zero

goroutine 73 [running]:
github.com/docker/buildx/driver/kubernetes/podchooser.(*RandomPodChooser).ChoosePod(0x140004cdac0, {0x1047017f0, 0x14000294720})
	/src/driver/kubernetes/podchooser/podchooser.go:37 +0x230
github.com/docker/buildx/driver/kubernetes/podchooser.(*StickyPodChooser).ChoosePod(0x14000734cf0, {0x1047017f0, 0x14000294720})
	/src/driver/kubernetes/podchooser/podchooser.go:68 +0x3d8
github.com/docker/buildx/driver/kubernetes.(*Driver).Client(0x14000713440, {0x1047017f0, 0x14000294720})
	/src/driver/kubernetes/driver.go:190 +0xa0
github.com/docker/buildx/driver.(*cachedDriver).Client.func1()
	/src/driver/manager.go:152 +0x48
sync.(*Once).doSlow(0x140001401e8, 0x140004cde08)
	/usr/local/go/src/sync/once.go:68 +0x10c
sync.(*Once).Do(...)
	/usr/local/go/src/sync/once.go:59
github.com/docker/buildx/driver.(*cachedDriver).Client(0x140001401c0, {0x1047017f0, 0x14000294720})
	/src/driver/manager.go:151 +0x6c
github.com/docker/buildx/commands.loadInfoData({0x1047017f0, 0x14000294720}, 0x14000140200)
	/src/commands/util.go:284 +0xbc
github.com/docker/buildx/commands.loadNodeGroupData.func1.1()
	/src/commands/util.go:315 +0x3c
golang.org/x/sync/errgroup.(*Group).Go.func1(0x140005188d0, 0x140007194e0)
	/src/vendor/golang.org/x/sync/errgroup/errgroup.go:57 +0x58
created by golang.org/x/sync/errgroup.(*Group).Go
	/src/vendor/golang.org/x/sync/errgroup/errgroup.go:54 +0x60
```

**Comment by metasim** [comment]
Also, `docker buildx ls` after the above panics, requiring `docker buildx rm` before anything will work again.

```
ERRO[0000] no pod found for key ""
panic: runtime error: integer divide by zero

goroutine 49 [running]:
github.com/docker/buildx/driver/kubernetes/podchooser.(*RandomPodChooser).ChoosePod(0x140006f1ac0, {0x1042957f0, 0x140003e8f00})
	/src/driver/kubernetes/podchooser/podchooser.go:37 +0x230
github.com/docker/buildx/driver/kubernetes/podchooser.(*StickyPodChooser).ChoosePod(0x140002e5920, {0x1042957f0, 0x140003e8f00})
	/src/driver/kubernetes/podchooser/podchooser.go:68 +0x3d8
github.com/docker/buildx/driver/kubernetes.(*Driver).Client(0x1400035e240, {0x1042957f0, 0x140003e8f00})
	/src/driver/kubernetes/driver.go:190 +0xa0
github.com/docker/buildx/driver.(*cachedDriver).Client.func1()
	/src/driver/manager.go:152 +0x48
sync.(*Once).doSlow(0x14000987da8, 0x140006f1e08)
	/usr/local/go/src/sync/once.go:68 +0x10c
sync.(*Once).Do(...)
	/usr/local/go/src/sync/once.go:59
github.com/docker/buildx/driver.(*cachedDriver).Client(0x14000987d80, {0x1042957f0, 0x140003e8f00})
	/src/driver/manager.go:151 +0x6c
github.com/docker/buildx/commands.loadInfoData({0x1042957f0, 0x140003e8f00}, 0x14000987dc0)
	/src/commands/util.go:284 +0xbc
github.com/docker/buildx/commands.loadNodeGroupData.func1.1()
	/src/commands/util.go:315 +0x3c
golang.org/x/sync/errgroup.(*Group).Go.func1(0x140004c8000, 0x14000a7d600)
	/src/vendor/golang.org/x/sync/errgroup/errgroup.go:57 +0x58
created by golang.org/x/sync/errgroup.(*Group).Go
	/src/vendor/golang.org/x/sync/errgroup/errgroup.go:54 +0x60
```

**Comment by tonistiigi** [comment]
@morlay @AkihiroSuda

**Comment by AkihiroSuda** [comment]
Are the pods crashing? Could you show the pod logs?

**Comment by metasim** [comment]
@AkihiroSuda Sorry I don't have more debug info right now; I've had to move on to other approaches. However, based on a simple visual inspection of the code, `ChoosePod` doesn't handle the case where `ListRunningPods` returns a zero length list.

https://github.com/docker/buildx/blob/ab09846df70df822fd32b9d0c715dc0605344618/driver/kubernetes/podchooser/podchooser.go#L28-L37

**Comment by Shaked** [comment]
Hey I have experienced the same issue. This happened because I had two buildkitd pods with different names but with the same labels selectors. So every time I ran either `docker buildx ls` or tried to create a builder with an existing pod, it ended up with: 

```
╰─$ docker buildx ls
ERROR: no pod found for key ""
ERROR: no pod found for key ""
panic: runtime error: integer divide by zero

goroutine 83 [running]:
github.com/docker/buildx/driver/kubernetes/podchooser.(*RandomPodChooser).ChoosePod(0xc000725b88, {0x2d949b0, 0xc000110180})
	/src/driver/kubernetes/podchooser/podchooser.go:37 +0x21d
github.com/docker/buildx/driver/kubernetes/podchooser.(*StickyPodChooser).ChoosePod(0xc0003b6e40, {0x2d949b0, 0xc000110180})
	/src/driver/kubernetes/podchooser/podchooser.go:68 +0x425
github.com/docker/buildx/driver/kubernetes.(*Driver).Client(0xc000128000, {0x2d949b0, 0xc000110180})
	/src/driver/kubernetes/driver.go:194 +0xba
github.com/docker/buildx/driver.(*cachedDriver).Client.func1()
	/src/driver/manager.go:152 +0x32
sync.(*Once).doSlow(0x0, 0xc000725ec0)
	/usr/local/go/src/sync/once.go:68 +0xd2
sync.(*Once).Do(...)
	/usr/local/go/src/sync/once.go:59
github.com/docker/buildx/driver.(*cachedDriver).Client(0xc0006949c0, {0x2d949b0, 0xc000110180})
	/src/driver/manager.go:151 +0x65
github.com/docker/buildx/commands.loadInfoData({0x2d949b0, 0xc000110180}, 0xc000694a00)
	/src/commands/util.go:286 +0xba
github.com/docker/buildx/commands.loadNodeGroupData.func1.1()
	/src/commands/util.go:315 +0x2a
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/src/vendor/golang.org/x/sync/errgroup/errgroup.go:57 +0x67
created by golang.org/x/sync/errgroup.(*Group).Go
	/src/vendor/golang.org/x/sync/errgroup/errgroup.go:54 +0x92
``` 

Is it even allowed to use more than one buildkitd pod? If not, maybe it would be better to throw a clear error somewhere around: 

https://github.com/docker/buildx/blob/3cf549a7f7ee015cabe99d4a08e4b9aabfc83ccc/driver/kubernetes/podchooser/podchooser.go#L74-L81 

Once I changed the identical labels, everything started to work.  Does that make any sense?

**Comment by jedevc** [comment]
> I'd like to be able to reuse an existing deployment for multiple clients rather than having to have separate ones running. The documentation isn't clear on whether this is possible or not, but when I try the command below, the CLI panics

This isn't a supported scenario as I understand it for the kubernetes driver - I think this sounds a lot more like a use case for the `remote` driver, which can either connect directly to either kubernetes pods, or tcp ports exposed by kubernetes services.

@Shaked could you share your command that you're using to create the driver?

**Comment by AkihiroSuda** [comment]
Seems fixed in https://github.com/docker/buildx/pull/1190
