### ISSUE TITLE
panic while using named contexts with platforms

### ISSUE THREAD

**Issue by crazy-max** [docker/buildx#978]
buildx v0.8.0-rc1

repro: https://github.com/crazy-max/buildx-buildkit-tests/tree/main/bake-multi

```dockerfile
FROM alpine:3.15
ARG TARGETPLATFORM
WORKDIR /src
RUN echo $TARGETPLATFORM > platform
```
> `baseapp.Dockerfile`

```dockerfile
# syntax=docker/dockerfile-upstream:master-labs
FROM baseapp
RUN cat platform
```
> `Dockerfile`

```dockerfile
# docker-bake.hcl
target "base" {
  dockerfile = "baseapp.Dockerfile"
  args = {
    basefoo = "bar"
  }
  platforms = [
    "linux/amd64",
    "linux/arm64"
  ]
}

target "app" {
  contexts = {
    baseapp = "target:base"
  }
}
```

```console
$ docker buildx bake --metadata-file metadata.json --set app.tags=user/app:latest --set app.output=type=cacheonly app
panic: runtime error: index out of range [0] with length 0

goroutine 157 [running]:
github.com/docker/buildx/build.Build.func4.1()
        /src/build/build.go:762 +0x62b
golang.org/x/sync/errgroup.(*Group).Go.func1()
        /src/vendor/golang.org/x/sync/errgroup/errgroup.go:57 +0x67
created by golang.org/x/sync/errgroup.(*Group).Go
        /src/vendor/golang.org/x/sync/errgroup/errgroup.go:54 +0x92
```

**Comment by tonistiigi** [comment]
Strange, I get no panic.

Instead, I get:

```
Dockerfile:2
--------------------
   1 |     # syntax=docker/dockerfile-upstream:master-labs
   2 | >>> FROM baseapp
   3 |     RUN cat platform
   4 |
--------------------
error: failed to solve: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
```

That would go away if `platform = ["linux/arm64"]` would be defined for the app target. Fixed this in https://github.com/moby/buildkit/pull/2693 . 

https://github.com/docker/buildx/pull/981 is another issue I discovered while debugging this.

**Comment by tonistiigi** [comment]
@crazy-max Do you still get a panic with the latest fixes? Or do you know what was different for me?

**Comment by crazy-max** [comment]
I still repro with https://github.com/docker/buildx/commit/6efcee28d59e1aa4d935e8d4055ca5c0edff0a4b, not sure why you can't.
